name: CI

on: [push]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "git@github.com:jsdrupal/admin_ui.git"
        SOURCE_BRANCH: "refs/remotes/source/*"
        DESTINATION_REPO: "git@git.drupal.org:project/admin_ui.git"
        DESTINATION_BRANCH: "refs/heads/*"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
