name: CI

on: [push]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.1.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: repo-sync
        run: |
          git remote add drupal git@git.drupal.org:project/admin_ui.git
          git push drupal HEAD
