name: CI

on: [push]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: repo-sync
        run: |
            mkdir -p ~/.ssh
            eval `ssh-agent -s`
            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
            git remote add drupal git@git.drupal.org:project/admin_ui.git
            git checkout -b local-branch
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git push drupal local-branch:$(echo -n ${GITHUB_REF} | sed 's/refs\/heads\///g')
