name: drupal.org sync

on:
  push:
    branches:
      - 8.x-1.x

jobs:
  push-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://node:13
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run the build
        run: yarn build
      - name: Push to remote branch
        run: |
            mkdir -p ~/.ssh
            eval `ssh-agent -s`
            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
            git config --global user.name "jsdrupal-bot"
            git config --global user.email "jsdrupal-bot@3630107.no-reply.drupal.org"
            git add -f dist
            git commit -m "Commit build artifacts"
            git remote add drupal git@git.drupal.org:project/admin_ui.git
            REMOTE_BRANCH=$(echo -n ${GITHUB_REF} | sed 's/refs\/heads\///g')
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
            # Delete the remote branch because drupal.org doesn't allow force push
            GIT_SSH_COMMAND=${GIT_SSH_COMMAND} git push drupal --delete ${REMOTE_BRANCH} || true
            GIT_SSH_COMMAND=${GIT_SSH_COMMAND} git checkout -b local-branch
            GIT_SSH_COMMAND=${GIT_SSH_COMMAND} git push drupal local-branch:${REMOTE_BRANCH}
