name: Test PHP

on:
  push:
    branches:
      - 8.x-1.x
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://composer:latest
      - name: Download Drupal
        run: |
          mkdir ../drupal
          cd ../drupal
          composer init -n --name=drupal/test_admin_ui --stability=dev
          composer require drupal-composer/drupal-scaffold composer/installers
          composer config repositories.drupal composer https://packages.drupal.org/8
          composer config repositories.admin_ui '{"type": "path", "url": "../admin_ui", "symlink": true}'
          composer require drupal/core:8.9.x-dev drupal/admin_ui:@dev
          ls -lha modules/contrib
